service: medium-api-proxy
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x

	
plugins:
  - serverless-plugin-lambda-insights

functions:
  # the node runtime function

  medium_node:
    handler: index.handler
    lambdaInsights: true
    events:
      - http:
          path: /posts_node
          method: get
          cors: true

  # the llrt runtime function
  medium_llrt:
    handler: llrtHandler.handler
    lambdaInsights: true
    runtime: provided.al2023
    layers:
      - arn:aws:lambda:us-east-1:408808605138:layer:llrt:1
    events:
      - http:
          path: /post_llrt
          method: get
          cors: true